
package Vistas;

import AccesoDatos.TipoHabitacionData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Entidades.*;

public class VistaTipoHabitacion extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo = new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int row, int colum){
        return false;
    }
};
   
    public VistaTipoHabitacion() {
        initComponents();
        armarCabecera();
        cargarTipoHabitacion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTipoHabitacion = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTCantPers = new javax.swing.JTextField();
        jTCantCamas = new javax.swing.JTextField();
        jTtipoCama = new javax.swing.JTextField();
        jTPrecioNoche = new javax.swing.JTextField();
        jBAgregar = new javax.swing.JButton();
        jBModifcar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("TIPOS DE HABITACIONES");

        jBSalir.setText("SALIR");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jTTipoHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTTipoHabitacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTTipoHabitacionKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTTipoHabitacion);

        jLabel2.setText("CANTIDAD DE PERSONAS");

        jLabel3.setText("CANTIDAD DE CAMAS");

        jLabel4.setText("TIPO DE CAMAS");

        jLabel5.setText("PRECIO POR NOCHE ");

        jTCantPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCantPersActionPerformed(evt);
            }
        });

        jTtipoCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtipoCamaActionPerformed(evt);
            }
        });

        jBAgregar.setText("AGREGAR");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBModifcar.setText("MODIFICAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBSalir))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(97, 97, 97)
                                .addComponent(jTPrecioNoche))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTCantPers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTtipoCama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTCantCamas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBModifcar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTCantPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTCantCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTtipoCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBModifcar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTPrecioNoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSalir)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAgregar)
                .addGap(135, 135, 135))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
      this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jTCantPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCantPersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCantPersActionPerformed

    private void jTtipoCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtipoCamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtipoCamaActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
     TipoHabitacion tipoHabit = new TipoHabitacion();
     TipoHabitacionData tipoHabitData = new TipoHabitacionData();
     if(!(jTCantCamas.getText().isEmpty() || jTCantPers.getText().isEmpty() || jTPrecioNoche.getText().isEmpty() || jTtipoCama.getText().isEmpty())){
       try{
           tipoHabit.setCantidadCamas(Integer.parseInt(jTCantCamas.getText()));
           tipoHabit.setCantidadPersonas(Integer.parseInt(jTCantPers.getText()));
           tipoHabit.setTipoCamas(jTtipoCama.getText());
           tipoHabit.setPrecioNoche(Double.parseDouble(jTPrecioNoche.getText()));
           tipoHabitData.insertarTipoHabitacion(tipoHabit);
           cargarTipoHabitacion();
           borrarFormulario();
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, "no se pudo agregar el tipo de habitacion");
       }
     }else{
         JOptionPane.showMessageDialog(this, "debe llenar todos los campos ");
     }
    
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jTTipoHabitacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTipoHabitacionKeyReleased
        if (jTTipoHabitacion.getSelectedRow() != -1) {
            int selectedRow = jTTipoHabitacion.getSelectedRow();

            // Obtener los valores de las celdas en las columnas 1, 2, 3 y 4
            Object cantPersObject = modelo.getValueAt(selectedRow, 1);
            Object cantCamasObject = modelo.getValueAt(selectedRow, 2);
            Object tipoCamaObject = modelo.getValueAt(selectedRow, 3);
            Object precioNocheObject = modelo.getValueAt(selectedRow, 4);
            
            //Asignar a los campos de texto los valores casteados con .toString
            jTCantPers.setText((cantPersObject).toString());
            jTCantCamas.setText((cantCamasObject).toString());
            jTtipoCama.setText((tipoCamaObject).toString());
            jTPrecioNoche.setText((precioNocheObject).toString());
        }
    }//GEN-LAST:event_jTTipoHabitacionKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBModifcar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCantCamas;
    private javax.swing.JTextField jTCantPers;
    private javax.swing.JTextField jTPrecioNoche;
    private javax.swing.JTable jTTipoHabitacion;
    private javax.swing.JTextField jTtipoCama;
    // End of variables declaration//GEN-END:variables
public void armarCabecera(){
    modelo.addColumn("IdTipoHabitacion");
    modelo.addColumn("Cantidad de Personas");
    modelo.addColumn("Cantidad de Camas");
    modelo.addColumn("Tipo de Camas");
    modelo.addColumn("Precio Por Noche");
    jTTipoHabitacion.setModel(modelo);
    
}
private void cargarTipoHabitacion(){
    List<TipoHabitacion> tipoHabitaciones = new ArrayList<>();
    TipoHabitacionData tipoHabitacionD = new TipoHabitacionData();
    tipoHabitaciones = tipoHabitacionD.consultaTipoHabitacion();
    eliminarFilas();
    for(TipoHabitacion tipoHabitacion:tipoHabitaciones){
        modelo.addRow(new Object[]{
            tipoHabitacion.getIdTipoHabitacion(),
            tipoHabitacion.getCantidadPersonas(),
            tipoHabitacion.getCantidadCamas(),
            tipoHabitacion.getTipoCamas(),
            tipoHabitacion.getPrecioNoche()
        });
    }
}
private void eliminarFilas() {
        int f = jTTipoHabitacion.getRowCount() - 1;
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }
private void borrarFormulario(){
    jTCantCamas.setText("");
    jTCantPers.setText("");
    jTPrecioNoche.setText("");
    jTtipoCama.setText("");
    
}
}
